import 'package:cloud_firestore/cloud_firestore.dart';

// Collection: API Key
// └── DocumentID: <auto-generated> (e.g., QoqYlSkXBmGo2u8ZNwwy)
//     • Gemini: string
//     • TextToSpeech: string

class ApiKeyHelper {
  static const String apiKeyTableName = 'API Key';

  static String _geminiApiKey = '';
  static String _textToSpeechApiKey = '';

  static String get geminiApiKey => _geminiApiKey;
  static String get textToSpeechApiKey => _textToSpeechApiKey;

  static bool get isLoaded =>
      _geminiApiKey.isNotEmpty && _textToSpeechApiKey.isNotEmpty;

  // Awaited in main() before runApp so the synchronous getters are populated by
  // the time any agent or TTS call runs.
  static Future<void> loadApiKeys() async {
    try {
      print("Fetching API keys from Firestore");
      QuerySnapshot apiKeySnapshot = await FirebaseFirestore.instance
          .collection(apiKeyTableName)
          .limit(1)
          .get();

      if (apiKeySnapshot.docs.isEmpty) {
        print('No document found in $apiKeyTableName collection');
        return;
      }

      var apiKeyData = apiKeySnapshot.docs.first.data() as Map<String, dynamic>;
      _geminiApiKey = apiKeyData['Gemini'] as String? ?? '';
      _textToSpeechApiKey = apiKeyData['TextToSpeech'] as String? ?? '';
      // Log presence only — never the key values themselves.
      print(
        'API keys loaded (Gemini: ${_geminiApiKey.isNotEmpty}, '
        'TextToSpeech: ${_textToSpeechApiKey.isNotEmpty})',
      );
    } catch (e) {
      print('Error loading API keys: $e');
    }
  }

  // Recovery path for call sites that can still run when the startup fetch
  // failed (offline cold start). A missing key otherwise surfaces only as an
  // opaque 400 from the Google APIs.
  static Future<void> ensureLoaded() async {
    if (isLoaded) return;
    await loadApiKeys();
  }
}
