import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:papa_pro_vision/Helper/DeviceHelper.dart';
import 'package:papa_pro_vision/enums.dart';
import 'package:package_info_plus/package_info_plus.dart';

// ================= FIRESTORE SCHEMA =================
//
// Collection: Organisations
// └── DocumentID: <auto-generated> (e.g., cFArsJaQkykKF0n003AE)
//     • NumberOfUsers: int
//     • OrgType: string
//     • CreatedAt: Timestamp
//     • ReferralKeys: List<DocumentReference> → /ReferralKey/{referralKeyID}
//
// Collection: ReferralKey
// └── DocumentID: <auto-generated> (e.g., esiVgNBkbvk8k0RCpPU6)
//     • NumberOfUsers: int
//     • KeyName: string
//     • MaxCount: int
//     • CreatedAt: Timestamp
//     • OrgID: DocumentReference → /Organisations/{orgID}
//     • SubscriptionBundleType: string
//     • SubscriptionEndDate: Timestamp
//     • SubscriptionTier: string
//
// Collection: Users
// └── DocumentID: <auto-generated> (e.g., oUkz7nJs1cxHZG4MLs9f)
//     • Analytics:
//     • CreatedAt: Timestamp
//     • Age: int
//     • Gender: string
//     • IsEnabled: bool
//     • IsAdmin: bool
//     • Name: string
//     • Occupation: string
//     • OrgID: DocumentReference → /Organisations/{orgID}
//     • ReferralKey: DocumentReference → /ReferralKey/{referralKeyID}
//     • UserUID: string
//     • APKVersion: string
//
// Collection: KilledAPKVersions
// └── DocumentID: <auto-generated> (e.g., oUkz7nJs1cxHZG4MLs9f)
//     • APKVersion: string
//     • CreatedAt: Timestamp
//     • ReasonMessage: string
//     • ReasonTitle: string
//
// ====================================================

class UserStatusResponse {
  final String? message;
  final String? reasonTitle;
  final UserStatus userStatus;
  final DocumentReference? referralKeyRef;

  UserStatusResponse({this.message, this.reasonTitle, required this.userStatus, this.referralKeyRef});
}

class ReferralKeyResponse {
  final String? message;
  final bool success;
  final DocumentReference? referralKeyRef;
  final DocumentReference? orgRef;

  ReferralKeyResponse({
    this.message,
    required this.success,
    this.referralKeyRef,
    this.orgRef,
  });
}

class CreateUserResponse {
  final String? message;
  final bool success;
  final DocumentReference? userRef;
  final DocumentReference? orgRef;
  final DocumentReference? referralKeyRef;

  CreateUserResponse({
    this.message,
    required this.success,
    this.userRef,
    this.orgRef,
    this.referralKeyRef,
  }){
    if(success){
      assert(userRef != null && orgRef != null && referralKeyRef != null, 'User, organization and referral key are required');
    }
  }
}

class KilledAPKVersionResponse {
  final bool isKilled;
  final String? reasonTitle;
  final String? reasonMessage;

  KilledAPKVersionResponse({required this.isKilled, this.reasonTitle, this.reasonMessage});
}

class DatabaseHelper {
  static const String usersTableName = 'Users';
  static const String organizationsTableName = 'Organisations';
  static const String referralKeyTableName = 'ReferralKey';
  static const String singleUserReferralKey = 'SINGLE_USER';
  static const String killedAPKVersionsTableName = 'KilledAPKVersions';

  static Future<CreateUserResponse> createUser({
    required String userUID,
    required int age,
    required String gender,
    required String name,
    required String phoneNumber,
    required String occupation,
    required UserType userType,
    DocumentReference? referralKeyRef,
    DocumentReference? orgRef,
  }) async {
    try {
      if (userUID.isEmpty) {
        // return CreateUserResponse(
        //   success: false,
        //   message: 'User not logged in. Please restart app and sign in using your phone number to continue.',
        // );
      }
      print('User UID: $userUID');
      if (userType == UserType.single) {
        print('Creating single user');
        orgRef = await FirebaseFirestore.instance
            .collection(organizationsTableName)
            .add({
              'NumberOfUsers': 1,
              'OrgType': (UserType.single.name).toString(),
              'ReferralKeys': [],
              'CreatedAt': FieldValue.serverTimestamp(),
            });

        referralKeyRef = await FirebaseFirestore.instance
            .collection(referralKeyTableName)
            .add({
              'NumberOfUsers': 1,
              'OrgID': orgRef,
              'SubscriptionBundleType': '',
              'SubscriptionEndDate': null,
              'SubscriptionTier': '',
              'CreatedAt': FieldValue.serverTimestamp(),
              'KeyName': singleUserReferralKey,
              'MaxCount': 1,
            });

        await orgRef.update({
          'ReferralKeys': FieldValue.arrayUnion([referralKeyRef]),
        });
        print('Single user org and referral key created');
      } else {
        // user Type is Organization
        if (referralKeyRef == null) {
          return CreateUserResponse(
            success: false,
            message:
                'Referral Key is required to register an organization user',
          );
        }
        if (orgRef == null) {
          return CreateUserResponse(
            success: false,
            message:
                'No organization associated with this referral key. Please contact your organization admin.',
          );
        }

        await referralKeyRef.update({'NumberOfUsers': FieldValue.increment(1)});
      }

      print('Creating user');
      PackageInfo packageInfo = await PackageInfo.fromPlatform();
      String APKVersion = '${packageInfo.version}+${packageInfo.buildNumber}';
      DocumentReference userRef = await FirebaseFirestore.instance
          .collection(usersTableName)
          .add({
            'Name': name,
            'Age': age,
            'Gender': gender,
            'IsAdmin': userType == UserType.single ? true : false,
            'Occupation': occupation.isEmpty ? null : occupation,
            'ReferralKey': referralKeyRef,
            'OrgID': orgRef,
            'IsEnabled': true,
            'UserUID': userUID.isEmpty ? phoneNumber : userUID,
            'CreatedAt': FieldValue.serverTimestamp(),
            'APKVersion': APKVersion,
            'Analytics': {
              'ResponseCount': 0,
              'TTSErrorCount': 0,
              'STTErrorCount': 0,
              'PromptErrorCount': 0,
              'CancelledRequestCount': 0,
              'ImageCaptureCount': 0,
              'LLMInteractionWithImageCount': 0,
              'JustLLMInteractionCount': 0,
              'SmartViewModeCount': 0,
              'ReaderModeCount': 0,
              'TranslationCount': 0,
              'MarathiResponseCount': 0,
              'EnglishResponseCount': 0,
            },
          });
      print('User created');
      return CreateUserResponse(
        success: true,
        userRef: userRef,
        orgRef: orgRef,
        referralKeyRef: referralKeyRef,
      );
    } catch (e) {
      print('Error creating user: $e');
      return CreateUserResponse(
        success: false,
        message: 'Something went wrong. Please try again later.',
      );
    }
  }

  static Future<ReferralKeyResponse> verifyReferralKey({
    required String referralKeyName,
  }) async {
    try {
      print("Verifying referral key: $referralKeyName");

      QuerySnapshot referralKey = await FirebaseFirestore.instance
          .collection(referralKeyTableName)
          .where('KeyName', isEqualTo: referralKeyName)
          .get();
      print("Referral key query done, found ${referralKey} documents");

      if (referralKey.docs.isNotEmpty) {
        // return ReferralKeyResponse(
        //   success: false,
        //   message:
        //       'Could not find referral key. Please cross check with your organization admin.',
        // );

        var referralKeyDoc = referralKey.docs.first;
        var referralKeyData = referralKeyDoc.data() as Map<String, dynamic>;
        if (referralKeyData['NumberOfUsers'] >= referralKeyData['MaxCount']) {
          return ReferralKeyResponse(
            success: false,
            message:
                'Referral key usage limit reached. Please contact your organization admin.',
          );
        }
        return ReferralKeyResponse(
          success: true,
          orgRef: referralKeyData['OrgID'] as DocumentReference,
          referralKeyRef: referralKeyDoc.reference,
        );
      } else {
        return ReferralKeyResponse(
          success: false,
          message:
              'Could not find referral key. Please cross check with your organization admin.',
        );
      }
    } catch (e) {
      print('Error verifying referral key: $e');
      return ReferralKeyResponse(
        success: false,
        message: 'Something went wrong. Please try again later.',
      );
    }
  }

  static Future<UserStatusResponse> checkUserStatus({
    required String userUID,
  }) async {
    print('Checking user status: $userUID');
    try {
      var isInternetAvailable =
          await Devicehelper.hasInternetConnectionAndNotify(
            methodCallName: 'checkUserStatus',
          );
      if (!isInternetAvailable) {
        return UserStatusResponse(userStatus: UserStatus.noInternet);
      }
      QuerySnapshot userDoc = await FirebaseFirestore.instance
          .collection(usersTableName)
          .where('UserUID', isEqualTo: userUID)
          .get();
      if (userDoc.docs.isNotEmpty) {
        if (userDoc.docs.length > 1) {
          return UserStatusResponse(
            message:
                'Multiple users found with the same phone number. Please contact support.',
            userStatus: UserStatus.errorState,
          );
        }
        Map<String, dynamic> userData = userDoc.docs[0].data() as Map<String, dynamic>;
        if (userData['IsEnabled'] ==
            false) {
          return UserStatusResponse(
            message: 'Your account is not active. Please contact support.',
            userStatus: UserStatus.errorState,
          );
        }
        KilledAPKVersionResponse killedAPKVersionResponse = await checkKilledAPKVersions(APKVersion: userData['APKVersion'] ?? '');
        if (killedAPKVersionResponse.isKilled) {
          return UserStatusResponse(
            message: killedAPKVersionResponse.reasonMessage,
            reasonTitle: killedAPKVersionResponse.reasonTitle,
            userStatus: UserStatus.apkKilled,
          );
        }

        DocumentSnapshot referralKeyDoc = await userData['ReferralKey'].get();
        if (referralKeyDoc.exists) {
          Map<String, dynamic> referralKeyData = referralKeyDoc.data() as Map<String, dynamic>;
          UserStatus userStatus = checkSubscriptionStatus(
            referralKeyData: referralKeyData,
          );
          return UserStatusResponse(userStatus: userStatus, referralKeyRef: referralKeyDoc.reference);
        }
      }
      return UserStatusResponse(userStatus: UserStatus.notRegistered);
    } catch (e) {
      print('Error checking if user exists: $e');
      return UserStatusResponse(
        message:
            'Something went wrong while checking if user exists. Please try again later.',
        userStatus: UserStatus.errorState,
      );
    }
  }

  static Future<KilledAPKVersionResponse> checkKilledAPKVersions({
    required String APKVersion,
  }) async {
    try {
      print("Checking killed APK versions: $APKVersion");
      QuerySnapshot killedAPKVersions = await FirebaseFirestore.instance
          .collection(killedAPKVersionsTableName)
          .where('APKVersion', isEqualTo: APKVersion)
          .get();
      print("Killed APK versions query done, found ${killedAPKVersions.docs.length} documents");
      if (killedAPKVersions.docs.isNotEmpty) {
        var killedAPKVersionDoc = killedAPKVersions.docs.first;
        var killedAPKVersionData = killedAPKVersionDoc.data() as Map<String, dynamic>;
        return KilledAPKVersionResponse(isKilled: true, reasonTitle: killedAPKVersionData['ReasonTitle'], reasonMessage: killedAPKVersionData['ReasonMessage']);
      }
      return KilledAPKVersionResponse(isKilled: false);
    } catch (e) {
      print('Error checking killed APK versions: $e');
      return KilledAPKVersionResponse(isKilled: false);
    }
  }

  static UserStatus checkSubscriptionStatus({
    required Map<String, dynamic> referralKeyData,
  }) {
    if (referralKeyData['SubscriptionEndDate'] == null) {
      return UserStatus.firstPaymentPending;
    }

    if (referralKeyData['SubscriptionEndDate'].toDate().isAfter(DateTime.now())) {
      return UserStatus.active;
    }

    return UserStatus.paymentPending;
  }

  static Future<void> setSubscriptionInformation({
    required DocumentReference referralKeyRef,
    required SubscriptionBundleType subscriptionBundleType,
  }) async {
    SubscriptionTier subscriptionTier = (subscriptionBundleType == SubscriptionBundleType.firstMonthFree ? SubscriptionTier.free : SubscriptionTier.paid);
    DateTime subscriptionEndDate = DateTime.now().add(Duration(days: subscriptionBundleType.getDaysDuration()));
    DocumentSnapshot referralKeyDoc = await referralKeyRef.get();
    if (referralKeyDoc.exists) {
      print('Updating subscription information for referral key: ${referralKeyRef.id}');
      await referralKeyRef.update({'SubscriptionBundleType': subscriptionBundleType.toString(), 'SubscriptionTier': subscriptionTier.toString(), 'SubscriptionEndDate': subscriptionEndDate});
    }
  }

}
