import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:papa_pro_vision/enums.dart';

// ================= FIRESTORE SCHEMA =================
//
// Collection: Organisations
// └── DocumentID: <auto-generated> (e.g., cFArsJaQkykKF0n003AE)
//     • NumberOfUsers: int
//     • OrgType: string
//     • ReferralKeys: List<DocumentReference> → /ReferralKey/{referralKeyID}
//
// Collection: ReferralKey
// └── DocumentID: <auto-generated> (e.g., esiVgNBkbvk8k0RCpPU6)
//     • NumberOfUsers: int
//     • OrgID: DocumentReference → /Organisations/{orgID}
//     • SubscriptionBundleType: string
//     • SubscriptionEndDate: Timestamp
//     • SubscriptionTier: string
//
// Collection: Users
// └── DocumentID: <auto-generated> (e.g., oUkz7nJs1cxHZG4MLs9f)
//     • Analytics:
//         ◦ CreatedAt: Timestamp
//         ◦ DoB: string
//         ◦ Gender: string
//         ◦ IsEnabled: bool
//         ◦ IsAdmin: string
//         ◦ Name: string
//         ◦ Occupation: string
//     • OrgID: DocumentReference → /Organisations/{orgID}
//     • ReferralKey: DocumentReference → /ReferralKey/{referralKeyID}
//     • UserUID: string
//
// ====================================================


class UserStatusResponse {
  final String? message;
  final UserStatus userStatus;

  UserStatusResponse({this.message, required this.userStatus});
}

class ReferralKeyResponse {
  final String? message;
  final bool success;
  final DocumentReference? referralKeyRef;
  final DocumentReference? orgRef;

  ReferralKeyResponse({this.message, required this.success,this.referralKeyRef, this.orgRef});
}

class CreateUserResponse {
  final String? message;
  final bool success;
  final DocumentReference? userRef;
  final DocumentReference? orgRef;
  final DocumentReference? referralKeyRef;

  CreateUserResponse({this.message, required this.success,this.userRef, this.orgRef, this.referralKeyRef});
}

class DatabaseHelper {
  static const String usersTableName = 'Users';
  static const String organizationsTableName = 'Organisations';
  static const String referralKeyTableName = 'ReferralKey';
  static const String singleUserReferralKey = 'SINGLE_USER';

  static Future<CreateUserResponse> createUser({
    required String userUID,
    required DateTime dob,
    required String gender,
    required String name,
    required String phoneNumber,
    required String occupation,
    required UserType userType,
    DocumentReference? referralKeyRef,
    DocumentReference? orgRef,
  }) async {
    try {
      if (userUID.isEmpty) {
        return CreateUserResponse(
          success: false,
          message: 'User not logged in. Please restart app and sign in using your phone number to continue.',
        );
      }
      if (userType == UserType.single) {
        print('Creating single user');
        orgRef = await FirebaseFirestore.instance
            .collection(organizationsTableName)
            .add({
              'NumberOfUsers': 1,
              'OrgType': UserType.single.toString(),
              'ReferralKeys': [],
            });

        referralKeyRef = await FirebaseFirestore.instance
            .collection(referralKeyTableName)
            .add({
              'NumberOfUsers': 1,
              'OrgID': orgRef,
              'SubscriptionBundleType': '',
              'SubscriptionEndDate': null,
              'SubscriptionTier': '',
            });

        await orgRef.update({
          'ReferralKeys': FieldValue.arrayUnion([referralKeyRef]),
        });
        print('Single user org and referral key created');
      } else {
        // user Type is Organization
        if (referralKeyRef == null) {
          return CreateUserResponse(
            success: false,
            message: 'Referral Key is required to register an organization user',
          );
        }
        if (orgRef == null) {
          return CreateUserResponse(
            success: false,
            message: 'No organization associated with this referral key. Please contact your organization admin.',
          );
        }

        await referralKeyRef.update({'NumberOfUsers': FieldValue.increment(1)});
      }

      print('Creating user');
      DocumentReference userRef = await FirebaseFirestore.instance
          .collection(usersTableName)
          .add({
            'Name': name,
            'DoB': dob.toIso8601String().isEmpty ? null : dob.toIso8601String(),
            'Gender': gender,
            'IsAdmin': userType == UserType.single ? true : false,
            'Occupation': occupation.isEmpty ? null : occupation,
            'ReferralKey': referralKeyRef,
            'OrgID': orgRef,
            'IsEnabled': true,
            'UserUID': userUID,
            'CreatedAt': FieldValue.serverTimestamp(),
            'Analytics': {
              'ResponseCount': 0,
              'TTSErrorCount': 0,
              'STTErrorCount': 0,
              'PromptErrorCount': 0,
              'CancelledRequestCount': 0,
              'ImageCaptureCount': 0,
              'LLMInteractionWithImageCount': 0,
              'JustLLMInteractionCount': 0,
              'SmartViewModeCount': 0,
              'ReaderModeCount': 0,
              'TranslationCount': 0,
              'MarathiResponseCount': 0,
              'EnglishResponseCount': 0,
            },
          });
      print('User created');
      return CreateUserResponse(
        success: true,
        userRef: userRef,
        orgRef: orgRef,
        referralKeyRef: referralKeyRef,
      );
    } catch (e) {
      print('Error creating user: $e');
      return CreateUserResponse(
        success: false,
        message: 'Something went wrong. Please try again later.',
      );
    }
  }

  static Future<ReferralKeyResponse> verifyReferralKey({
    required String referralKey,
  }) async {
    try {
      DocumentSnapshot referralKeyDoc = await FirebaseFirestore.instance
          .collection(referralKeyTableName)
          .doc(referralKey)
          .get();
      if (!referralKeyDoc.exists) {
          return ReferralKeyResponse(
            success: false,
            message: 'Could not find referral key. Please cross check with your organization admin.',
          );
        }
        var referralKeyData = referralKeyDoc.data() as Map<String, dynamic>;
        if (referralKeyData['NumberOfUsers'] >= referralKeyData['MaxCount']) {
          return ReferralKeyResponse(
            success: false,
            message: 'Referral key usage limit reached. Please contact your organization admin.',
          );
        }
      return ReferralKeyResponse(
        success: true,
        orgRef: referralKeyData['OrgID'] as DocumentReference,
        referralKeyRef: referralKeyDoc.reference,
      );
    } catch (e) {
      print('Error verifying referral key: $e');
      return ReferralKeyResponse(
        success: false,
        message: 'Something went wrong. Please try again later.',
      );
    }
  }

  static Future<UserStatusResponse> checkUserStatus({
    required String userUID,
  }) async {
    try {
      QuerySnapshot userDoc = await FirebaseFirestore.instance
          .collection(usersTableName)
          .where('UserUID', isEqualTo: userUID)
          .get();
      if (userDoc.docs.isNotEmpty) {
        if(userDoc.docs.length > 1) {
          return UserStatusResponse(
            message: 'Multiple users found with the same phone number. Please contact support.',
            userStatus: UserStatus.errorState,
          );
        }
        if((userDoc.docs[0].data() as Map<String, dynamic>?)?['IsEnabled'] == false) {
          return UserStatusResponse(
            message: 'Your account is not active. Please contact support.',
            userStatus: UserStatus.errorState,
          );
        }
        UserStatus userStatus = checkSubscriptionStatus(userDoc: userDoc.docs[0]);
        return UserStatusResponse(
          userStatus: userStatus
        );
      }
      return UserStatusResponse(
        userStatus: UserStatus.notRegistered,
      );
    } catch (e) {
      print('Error checking if user exists: $e');
      return UserStatusResponse(
        message: 'Something went wrong while checking if user exists. Please try again later.',
        userStatus: UserStatus.errorState,
      );
    }
  }


  static UserStatus checkSubscriptionStatus({required QueryDocumentSnapshot userDoc}){
    var userData = userDoc.data() as Map<String, dynamic>;

    if(userData['SubscriptionEndDate'] == null) {
      return UserStatus.firstPaymentPending;
    }

    if(userData['SubscriptionEndDate'].isAfter(DateTime.now())) {
      return UserStatus.active;
    }

    return UserStatus.paymentPending;
  }
  }
